---
- name: My play for K8s deployment
  hosts: ekshost
  tasks:
    - name: Pull docker image
      command: docker pull sushila91/surajit:contact_backend_app
    - name: Copy K8s deployment file
      copy:
       src: Deployment.yml
       dest: /home/ansadmin/backend
    - name: K8s Delete Deployment
      command: kubectl delete deployment contactbackendappdeployment
    - name: K8s deployment
      command: kubectl apply -f /home/ansadmin/backend/Deployment.yml
...
      
      
      
      
