---
- name: Frist play - Copy Docker file, Copy artifat, Create docker image and push docker image
  hosts: docker
  tasks:
    - name: Copy Dockerfile
      copy:
       src: Dockerfile
       dest: /home/ansadmin/backend
    - name: Copy artifact
      copy:
       src: target
       dest: /home/ansadmin/backend
    - name: Build docker image
      command: docker build -t sushila91/surajit:contact_backend_app  /home/ansadmin/backend
    - name: Push docker image
      command: docker push sushila91/surajit:contact_backend_app
...      
      
